apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: github-application
  template:
    metadata:
      labels:
        app: github-application
    spec:
      containers:
        - name: github-springboot
          image: gyandoc/jhooq-docker-demo:jhooq-docker-demo
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: github-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: github-springboot
